apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openberth.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openberth.labels" . | nindent 4 }}
data:
  config.json: |
    {
      "domain": {{ .Values.domain | quote }},
      "port": {{ .Values.service.port }},
      "defaultTTLHours": {{ .Values.defaultTTLHours }},
      "defaultMaxDeploys": {{ .Values.defaultMaxDeploys }},
      "insecure": {{ .Values.insecure }},
      "backend": "kubernetes",
      "containerDefaults": {
        "memory": {{ .Values.containerDefaults.memory | quote }},
        "cpus": {{ .Values.containerDefaults.cpus | quote }},
        "pidsLimit": {{ .Values.containerDefaults.pidsLimit }}
      }
    }
